# Generated by Django 5.0.4 on 2024-04-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_books_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
